import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { tr, en, ar, ku, uz, az, de }

final languageProvider =
    StateNotifierProvider<LanguageNotifier, AppLanguage>((ref) => LanguageNotifier());

class LanguageNotifier extends StateNotifier<AppLanguage> {
  static const String _key = 'app_language';
  LanguageNotifier() : super(AppLanguage.tr) {
    _load();
  }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    final idx = prefs.getInt(_key);
    if (idx != null && idx < AppLanguage.values.length) {
      state = AppLanguage.values[idx];
    }
  }

  Future<void> setLanguage(AppLanguage lang) async {
    state = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_key, lang.index);
  }

  bool get isRtl => state == AppLanguage.ar || state == AppLanguage.ku;

  Locale get locale {
    switch (state) {
      case AppLanguage.tr:
        return const Locale('tr', 'TR');
      case AppLanguage.en:
        return const Locale('en', 'US');
      case AppLanguage.ar:
        return const Locale('ar', 'IQ');
      case AppLanguage.ku:
        return const Locale('ku', 'IQ');
      case AppLanguage.uz:
        return const Locale('uz', 'UZ');
      case AppLanguage.az:
        return const Locale('az', 'AZ');
      case AppLanguage.de:
        return const Locale('de', 'DE');
    }
  }
}

class L {
  static String get(String key, AppLanguage lang) {
    return _translations[key]?[lang] ?? _translations[key]?[AppLanguage.tr] ?? key;
  }

  static final Map<String, Map<AppLanguage, String>> _translations = {
    'app_name': {
      AppLanguage.tr: 'RestEx',
      AppLanguage.en: 'RestEx',
      AppLanguage.ar: 'RestEx',
      AppLanguage.ku: 'RestEx',
      AppLanguage.uz: 'RestEx',
      AppLanguage.az: 'RestEx',
      AppLanguage.de: 'RestEx',
    },
    'tables': {
      AppLanguage.tr: 'Masa',
      AppLanguage.en: 'Table',
      AppLanguage.ar: 'طاولة',
      AppLanguage.ku: 'مێز',
      AppLanguage.uz: 'Stol',
      AppLanguage.az: 'Masa',
      AppLanguage.de: 'Tisch',
    },
    'waiter_request': {
      AppLanguage.tr: 'Garson talebi',
      AppLanguage.en: 'Waiter request',
      AppLanguage.ar: 'طلب نادل',
      AppLanguage.ku: 'داوای گارسۆن',
      AppLanguage.uz: 'Ofitsiant so\'rovi',
      AppLanguage.az: 'Ofisiant tələbi',
      AppLanguage.de: 'Kellnerruf',
    },
    'fiscal_day': {
      AppLanguage.tr: 'MALİ GÜN',
      AppLanguage.en: 'FISCAL DAY',
      AppLanguage.ar: 'يوم مالي',
      AppLanguage.ku: 'ڕۆژی دارایی',
      AppLanguage.uz: 'MOLIYA KUNI',
      AppLanguage.az: 'MALİYYƏ GÜNÜ',
      AppLanguage.de: 'GESCHÄFTSTAG',
    },
    'occupied': {
      AppLanguage.tr: 'DOLU',
      AppLanguage.en: 'OCCUPIED',
      AppLanguage.ar: 'مشغول',
      AppLanguage.ku: 'داگیرکراو',
      AppLanguage.uz: 'BAND',
      AppLanguage.az: 'DOLU',
      AppLanguage.de: 'BESETZT',
    },
    'available': {
      AppLanguage.tr: 'BOŞ',
      AppLanguage.en: 'AVAILABLE',
      AppLanguage.ar: 'متاح',
      AppLanguage.ku: 'بەتاڵ',
      AppLanguage.uz: 'BO\'SH',
      AppLanguage.az: 'BOŞ',
      AppLanguage.de: 'FREI',
    },
    'close_day': {
      AppLanguage.tr: 'GÜNÜ KAPAT',
      AppLanguage.en: 'CLOSE DAY',
      AppLanguage.ar: 'إغلاق اليوم',
      AppLanguage.ku: 'داخستنی ڕۆژ',
      AppLanguage.uz: 'KUNNI YOPISH',
      AppLanguage.az: 'GÜNÜ BAĞLA',
      AppLanguage.de: 'TAG SCHLIEßEN',
    },
    'table_status': {
      AppLanguage.tr: 'MASA DURUMU',
      AppLanguage.en: 'TABLE STATUS',
      AppLanguage.ar: 'حالة الطاولة',
      AppLanguage.ku: 'بارودۆخی مێز',
      AppLanguage.uz: 'STOL HOLATI',
      AppLanguage.az: 'MASA STATUSU',
      AppLanguage.de: 'TISCHSTATUS',
    },
    'available_table': {
      AppLanguage.tr: 'MÜSAİT MASA',
      AppLanguage.en: 'AVAILABLE TABLE',
      AppLanguage.ar: 'طاولة متاحة',
      AppLanguage.ku: 'مێزی بەردەست',
      AppLanguage.uz: 'BO\'SH STOL',
      AppLanguage.az: 'BOŞ MASA',
      AppLanguage.de: 'FREIER TISCH',
    },
    'service': {
      AppLanguage.tr: 'SERVİS',
      AppLanguage.en: 'SERVICE',
      AppLanguage.ar: 'الخدمة',
      AppLanguage.ku: 'خزمەتگوزاری',
      AppLanguage.uz: 'XIZMAT',
      AppLanguage.az: 'SERVİS',
      AppLanguage.de: 'SERVICE',
    },
    'package_service': {
      AppLanguage.tr: 'PAKET SERVİS',
      AppLanguage.en: 'DELIVERY',
      AppLanguage.ar: 'توصيل',
      AppLanguage.ku: 'گەیاندن',
      AppLanguage.uz: 'YETKAZIB BERISH',
      AppLanguage.az: 'ÇATDIRMA',
      AppLanguage.de: 'LIEFERUNG',
    },
    'retail': {
      AppLanguage.tr: 'PERAKENDE',
      AppLanguage.en: 'RETAIL',
      AppLanguage.ar: 'تجزئة',
      AppLanguage.ku: 'فرۆشتنی تاک',
      AppLanguage.uz: 'CHAKANA',
      AppLanguage.az: 'PƏRAKƏNDƏ',
      AppLanguage.de: 'EINZELHANDEL',
    },
    'takeaway': {
      AppLanguage.tr: 'GEL AL',
      AppLanguage.en: 'TAKEAWAY',
      AppLanguage.ar: 'استلام',
      AppLanguage.ku: 'ببەرە',
      AppLanguage.uz: 'OLIB KETISH',
      AppLanguage.az: 'GÖTÜR',
      AppLanguage.de: 'MITNEHMEN',
    },
    'self_service': {
      AppLanguage.tr: 'SELF SERVİS',
      AppLanguage.en: 'SELF SERVICE',
      AppLanguage.ar: 'خدمة ذاتية',
      AppLanguage.ku: 'خزمەتی خۆیی',
      AppLanguage.uz: 'O\'Z-O\'ZIGA XIZMAT',
      AppLanguage.az: 'SELF SERVİS',
      AppLanguage.de: 'SELBSTBEDIENUNG',
    },
    'orders': {
      AppLanguage.tr: 'SİPARİŞLER',
      AppLanguage.en: 'ORDERS',
      AppLanguage.ar: 'الطلبات',
      AppLanguage.ku: 'داواکارییەکان',
      AppLanguage.uz: 'BUYURTMALAR',
      AppLanguage.az: 'SİFARİŞLƏR',
      AppLanguage.de: 'BESTELLUNGEN',
    },
    'void_report': {
      AppLanguage.tr: 'İPTAL / İADE RAPORU',
      AppLanguage.en: 'VOID / RETURN REPORT',
      AppLanguage.ar: 'تقرير الإلغاء / الإرجاع',
      AppLanguage.ku: 'ڕاپۆرتی هەڵوەشاندنەوە',
      AppLanguage.uz: 'BEKOR / QAYTARISH',
      AppLanguage.az: 'LƏĞV / QAYTARMA',
      AppLanguage.de: 'STORNO / RETOURE',
    },
    'product_qty': {
      AppLanguage.tr: 'ÜRÜN SATIŞ ADEDİ',
      AppLanguage.en: 'PRODUCT QTY SOLD',
      AppLanguage.ar: 'كمية المبيعات',
      AppLanguage.ku: 'ژمارەی فرۆشراو',
      AppLanguage.uz: 'SOTILGAN SONI',
      AppLanguage.az: 'SATILAN SAY',
      AppLanguage.de: 'VERKAUFTE MENGE',
    },
    'reservations': {
      AppLanguage.tr: 'REZERVASYON',
      AppLanguage.en: 'RESERVATIONS',
      AppLanguage.ar: 'الحجوزات',
      AppLanguage.ku: 'حجزکردنەکان',
      AppLanguage.uz: 'BRON QILISH',
      AppLanguage.az: 'REZERVASYON',
      AppLanguage.de: 'RESERVIERUNGEN',
    },
    'customers': {
      AppLanguage.tr: 'MÜŞTERİLER',
      AppLanguage.en: 'CUSTOMERS',
      AppLanguage.ar: 'العملاء',
      AppLanguage.ku: 'کڕیارەکان',
      AppLanguage.uz: 'MIJOZLAR',
      AppLanguage.az: 'MÜŞTƏRİLƏR',
      AppLanguage.de: 'KUNDEN',
    },
    'reports': {
      AppLanguage.tr: 'RAPORLAR',
      AppLanguage.en: 'REPORTS',
      AppLanguage.ar: 'التقارير',
      AppLanguage.ku: 'ڕاپۆرتەکان',
      AppLanguage.uz: 'HISOBOTLAR',
      AppLanguage.az: 'HESABATLAR',
      AppLanguage.de: 'BERICHTE',
    },
    'stock': {
      AppLanguage.tr: 'STOK',
      AppLanguage.en: 'STOCK',
      AppLanguage.ar: 'المخزون',
      AppLanguage.ku: 'کۆگا',
      AppLanguage.uz: 'OMBOR',
      AppLanguage.az: 'ANBAR',
      AppLanguage.de: 'LAGER',
    },
    'cash': {
      AppLanguage.tr: 'KASA',
      AppLanguage.en: 'CASH',
      AppLanguage.ar: 'الصندوق',
      AppLanguage.ku: 'سندوق',
      AppLanguage.uz: 'KASSA',
      AppLanguage.az: 'KASSA',
      AppLanguage.de: 'KASSE',
    },
    'smart_table': {
      AppLanguage.tr: 'AKILLI MASA',
      AppLanguage.en: 'SMART TABLE',
      AppLanguage.ar: 'طاولة ذكية',
      AppLanguage.ku: 'مێزی زیرەک',
      AppLanguage.uz: 'AQLLI STOL',
      AppLanguage.az: 'AĞILLI MASA',
      AppLanguage.de: 'SMART TISCH',
    },
    'kitchen': {
      AppLanguage.tr: 'MUTFAK PANELİ',
      AppLanguage.en: 'KITCHEN DISPLAY',
      AppLanguage.ar: 'شاشة المطبخ',
      AppLanguage.ku: 'پانێلی چێشتخانە',
      AppLanguage.uz: 'OSHXONA PANELI',
      AppLanguage.az: 'MƏTBƏX PANELİ',
      AppLanguage.de: 'KÜCHENDISPLAY',
    },
    'recipes': {
      AppLanguage.tr: 'REÇETELER',
      AppLanguage.en: 'RECIPES',
      AppLanguage.ar: 'الوصفات',
      AppLanguage.ku: 'ڕێچەتەکان',
      AppLanguage.uz: 'RETSEPTLAR',
      AppLanguage.az: 'RESEPTLƏR',
      AppLanguage.de: 'REZEPTE',
    },
    'settings': {
      AppLanguage.tr: 'AYARLAR',
      AppLanguage.en: 'SETTINGS',
      AppLanguage.ar: 'الإعدادات',
      AppLanguage.ku: 'ڕێکخستنەکان',
      AppLanguage.uz: 'SOZLAMALAR',
      AppLanguage.az: 'AYARLAR',
      AppLanguage.de: 'EINSTELLUNGEN',
    },
    'management': {
      AppLanguage.tr: 'YÖNETİM',
      AppLanguage.en: 'MANAGEMENT',
      AppLanguage.ar: 'الإدارة',
      AppLanguage.ku: 'بەڕێوەبردن',
      AppLanguage.uz: 'BOSHQARUV',
      AppLanguage.az: 'İDARƏETMƏ',
      AppLanguage.de: 'VERWALTUNG',
    },
    'back': {
      AppLanguage.tr: 'GERİ',
      AppLanguage.en: 'BACK',
      AppLanguage.ar: 'رجوع',
      AppLanguage.ku: 'گەڕانەوە',
      AppLanguage.uz: 'ORQAGA',
      AppLanguage.az: 'GERİ',
      AppLanguage.de: 'ZURÜCK',
    },
    'search_table': {
      AppLanguage.tr: 'Masa veya sipariş ara...',
      AppLanguage.en: 'Search table or order...',
      AppLanguage.ar: 'ابحث عن طاولة أو طلب...',
      AppLanguage.ku: 'گەڕان بۆ مێز یان داواکاری...',
      AppLanguage.uz: 'Stol yoki buyurtma qidirish...',
      AppLanguage.az: 'Masa və ya sifariş axtar...',
      AppLanguage.de: 'Tisch oder Bestellung suchen...',
    },
    'all': {
      AppLanguage.tr: 'TÜMÜ',
      AppLanguage.en: 'ALL',
      AppLanguage.ar: 'الكل',
      AppLanguage.ku: 'هەمووی',
      AppLanguage.uz: 'HAMMASI',
      AppLanguage.az: 'HAMISI',
      AppLanguage.de: 'ALLE',
    },
    'add_region': {
      AppLanguage.tr: 'BÖLGE EKLE',
      AppLanguage.en: 'ADD REGION',
      AppLanguage.ar: 'إضافة منطقة',
      AppLanguage.ku: 'ناوچە زیادبکە',
      AppLanguage.uz: 'HUDUD QO\'SHISH',
      AppLanguage.az: 'BÖLGƏ ƏLAVƏ ET',
      AppLanguage.de: 'BEREICH HINZUFÜGEN',
    },
    'delete_region': {
      AppLanguage.tr: 'BÖLGE SİL',
      AppLanguage.en: 'DELETE REGION',
      AppLanguage.ar: 'حذف منطقة',
      AppLanguage.ku: 'ناوچە بسڕەوە',
      AppLanguage.uz: 'HUDUDNI O\'CHIRISH',
      AppLanguage.az: 'BÖLGƏ SİL',
      AppLanguage.de: 'BEREICH LÖSCHEN',
    },
    'add_table': {
      AppLanguage.tr: 'MASA EKLE',
      AppLanguage.en: 'ADD TABLE',
      AppLanguage.ar: 'إضافة طاولة',
      AppLanguage.ku: 'مێز زیادبکە',
      AppLanguage.uz: 'STOL QO\'SHISH',
      AppLanguage.az: 'MASA ƏLAVƏ ET',
      AppLanguage.de: 'TISCH HINZUFÜGEN',
    },
    'open_table': {
      AppLanguage.tr: 'MASAYI AÇ',
      AppLanguage.en: 'OPEN TABLE',
      AppLanguage.ar: 'فتح الطاولة',
      AppLanguage.ku: 'مێز بکەرەوە',
      AppLanguage.uz: 'STOLNI OCHISH',
      AppLanguage.az: 'MASANI AÇ',
      AppLanguage.de: 'TISCH ÖFFNEN',
    },
    'cancel': {
      AppLanguage.tr: 'VAZGEÇ',
      AppLanguage.en: 'CANCEL',
      AppLanguage.ar: 'إلغاء',
      AppLanguage.ku: 'پاشگەزبوونەوە',
      AppLanguage.uz: 'BEKOR',
      AppLanguage.az: 'LƏĞV ET',
      AppLanguage.de: 'ABBRECHEN',
    },
    'guest_count': {
      AppLanguage.tr: 'KİŞİ SAYISI',
      AppLanguage.en: 'GUEST COUNT',
      AppLanguage.ar: 'عدد الضيوف',
      AppLanguage.ku: 'ژمارەی میوان',
      AppLanguage.uz: 'MEHMONLAR SONI',
      AppLanguage.az: 'QONAQ SAYI',
      AppLanguage.de: 'GÄSTEANZAHL',
    },
    'person': {
      AppLanguage.tr: 'kişi',
      AppLanguage.en: 'guests',
      AppLanguage.ar: 'ضيف',
      AppLanguage.ku: 'میوان',
      AppLanguage.uz: 'kishi',
      AppLanguage.az: 'nəfər',
      AppLanguage.de: 'Gäste',
    },
    'waiter': {
      AppLanguage.tr: 'GARSON',
      AppLanguage.en: 'WAITER',
      AppLanguage.ar: 'نادل',
      AppLanguage.ku: 'گارسۆن',
      AppLanguage.uz: 'OFITSIANT',
      AppLanguage.az: 'OFİSİANT',
      AppLanguage.de: 'KELLNER',
    },
    'change': {
      AppLanguage.tr: 'DEĞİŞTİR',
      AppLanguage.en: 'CHANGE',
      AppLanguage.ar: 'تغيير',
      AppLanguage.ku: 'گۆڕین',
      AppLanguage.uz: 'O\'ZGARTIRISH',
      AppLanguage.az: 'DƏYİŞ',
      AppLanguage.de: 'ÄNDERN',
    },
    'empty_status': {
      AppLanguage.tr: 'BOŞ',
      AppLanguage.en: 'EMPTY',
      AppLanguage.ar: 'فارغ',
      AppLanguage.ku: 'بەتاڵ',
      AppLanguage.uz: 'BO\'SH',
      AppLanguage.az: 'BOŞ',
      AppLanguage.de: 'FREI',
    },
    'occupied_status': {
      AppLanguage.tr: 'DOLU',
      AppLanguage.en: 'OCCUPIED',
      AppLanguage.ar: 'مشغول',
      AppLanguage.ku: 'داگیرکراو',
      AppLanguage.uz: 'BAND',
      AppLanguage.az: 'DOLU',
      AppLanguage.de: 'BESETZT',
    },
    'kitchen_status': {
      AppLanguage.tr: 'MUTFAKTA',
      AppLanguage.en: 'IN KITCHEN',
      AppLanguage.ar: 'في المطبخ',
      AppLanguage.ku: 'لە چێشتخانە',
      AppLanguage.uz: 'OSHXONADA',
      AppLanguage.az: 'MƏTBƏXDƏ',
      AppLanguage.de: 'IN KÜCHE',
    },
    'served_status': {
      AppLanguage.tr: 'SERVİSTE',
      AppLanguage.en: 'SERVED',
      AppLanguage.ar: 'تم التقديم',
      AppLanguage.ku: 'خزمەتکرا',
      AppLanguage.uz: 'BERILDI',
      AppLanguage.az: 'TƏQDİM EDİLDİ',
      AppLanguage.de: 'SERVIERT',
    },
    'billing_status': {
      AppLanguage.tr: 'HESAP',
      AppLanguage.en: 'BILLING',
      AppLanguage.ar: 'الفاتورة',
      AppLanguage.ku: 'حساب',
      AppLanguage.uz: 'HISOB',
      AppLanguage.az: 'HESAB',
      AppLanguage.de: 'RECHNUNG',
    },
    'cleaning_status': {
      AppLanguage.tr: 'TEMİZLİK',
      AppLanguage.en: 'CLEANING',
      AppLanguage.ar: 'تنظيف',
      AppLanguage.ku: 'پاککردنەوە',
      AppLanguage.uz: 'TOZALASH',
      AppLanguage.az: 'TƏMİZLİK',
      AppLanguage.de: 'REINIGUNG',
    },
    'login': {
      AppLanguage.tr: 'Giriş Yap',
      AppLanguage.en: 'Login',
      AppLanguage.ar: 'تسجيل الدخول',
      AppLanguage.ku: 'چوونەژوورەوە',
      AppLanguage.uz: 'Kirish',
      AppLanguage.az: 'Daxil ol',
      AppLanguage.de: 'Anmelden',
    },
    'select_staff': {
      AppLanguage.tr: 'Personel Seçin',
      AppLanguage.en: 'Select Staff',
      AppLanguage.ar: 'اختر الموظف',
      AppLanguage.ku: 'کارمەند هەڵبژێرە',
      AppLanguage.uz: 'Xodimni tanlang',
      AppLanguage.az: 'Personal seçin',
      AppLanguage.de: 'Personal wählen',
    },
    'login_as': {
      AppLanguage.tr: 'olarak giriş',
      AppLanguage.en: 'login as',
      AppLanguage.ar: 'تسجيل الدخول كـ',
      AppLanguage.ku: 'چوونەژوورەوە وەک',
      AppLanguage.uz: 'sifatida kirish',
      AppLanguage.az: 'olaraq daxil ol',
      AppLanguage.de: 'anmelden als',
    },
    'connection_ok': {
      AppLanguage.tr: 'Bağlı',
      AppLanguage.en: 'Connected',
      AppLanguage.ar: 'متصل',
      AppLanguage.ku: 'پەیوەندی هەیە',
      AppLanguage.uz: 'Ulangan',
      AppLanguage.az: 'Bağlı',
      AppLanguage.de: 'Verbunden',
    },
    'connection_none': {
      AppLanguage.tr: 'Bağlantı Yok',
      AppLanguage.en: 'No Connection',
      AppLanguage.ar: 'لا يوجد اتصال',
      AppLanguage.ku: 'پەیوەندی نییە',
      AppLanguage.uz: 'Aloqa yo\'q',
      AppLanguage.az: 'Bağlantı yoxdur',
      AppLanguage.de: 'Keine Verbindung',
    },
    'checking': {
      AppLanguage.tr: 'Kontrol...',
      AppLanguage.en: 'Checking...',
      AppLanguage.ar: 'جاري الفحص...',
      AppLanguage.ku: 'پشکنین...',
      AppLanguage.uz: 'Tekshirilmoqda...',
      AppLanguage.az: 'Yoxlanılır...',
      AppLanguage.de: 'Prüfe...',
    },
    'subtotal': {
      AppLanguage.tr: 'Ara toplam',
      AppLanguage.en: 'Subtotal',
      AppLanguage.ar: 'المجموع الفرعي',
      AppLanguage.ku: 'کۆی لاوەکی',
      AppLanguage.uz: 'Oraliq summa',
      AppLanguage.az: 'Ara cəm',
      AppLanguage.de: 'Zwischensumme',
    },
    'total': {
      AppLanguage.tr: 'Toplam',
      AppLanguage.en: 'Total',
      AppLanguage.ar: 'المجموع',
      AppLanguage.ku: 'کۆی گشتی',
      AppLanguage.uz: 'Jami',
      AppLanguage.az: 'Cəm',
      AppLanguage.de: 'Gesamt',
    },
    'net_payment': {
      AppLanguage.tr: 'NET ÖDEME',
      AppLanguage.en: 'NET PAYMENT',
      AppLanguage.ar: 'الدفع الصافي',
      AppLanguage.ku: 'پارەدانی نێت',
      AppLanguage.uz: 'SOFF TO\'LOV',
      AppLanguage.az: 'NET ÖDƏMƏ',
      AppLanguage.de: 'NETTO ZAHLUNG',
    },
    'cash_payment': {
      AppLanguage.tr: 'NAKİT',
      AppLanguage.en: 'CASH',
      AppLanguage.ar: 'نقداً',
      AppLanguage.ku: 'نەقد',
      AppLanguage.uz: 'NAQD',
      AppLanguage.az: 'NAĞ',
      AppLanguage.de: 'BAR',
    },
    'card_payment': {
      AppLanguage.tr: 'K. KARTI',
      AppLanguage.en: 'CARD',
      AppLanguage.ar: 'بطاقة',
      AppLanguage.ku: 'کارت',
      AppLanguage.uz: 'KARTA',
      AppLanguage.az: 'KART',
      AppLanguage.de: 'KARTE',
    },
    'split_payment': {
      AppLanguage.tr: 'PARÇALI',
      AppLanguage.en: 'SPLIT',
      AppLanguage.ar: 'تقسيم',
      AppLanguage.ku: 'دابەشکردن',
      AppLanguage.uz: 'BO\'LIB',
      AppLanguage.az: 'BÖLÜŞMƏ',
      AppLanguage.de: 'GETEILT',
    },
    'print': {
      AppLanguage.tr: 'Yazdır',
      AppLanguage.en: 'Print',
      AppLanguage.ar: 'طباعة',
      AppLanguage.ku: 'چاپکردن',
      AppLanguage.uz: 'Chop etish',
      AppLanguage.az: 'Çap et',
      AppLanguage.de: 'Drucken',
    },
    'close_without_print': {
      AppLanguage.tr: 'Yazdırmadan kapat',
      AppLanguage.en: 'Close without print',
      AppLanguage.ar: 'إغلاق بدون طباعة',
      AppLanguage.ku: 'داخستن بێ چاپ',
      AppLanguage.uz: 'Chopsiz yopish',
      AppLanguage.az: 'Çapsız bağla',
      AppLanguage.de: 'Ohne Druck schließen',
    },
    'payment_method': {
      AppLanguage.tr: 'Ödeme Yöntemi',
      AppLanguage.en: 'Payment Method',
      AppLanguage.ar: 'طريقة الدفع',
      AppLanguage.ku: 'شێوازی پارەدان',
      AppLanguage.uz: 'To\'lov usuli',
      AppLanguage.az: 'Ödəmə üsulu',
      AppLanguage.de: 'Zahlungsart',
    },
    'discount': {
      AppLanguage.tr: 'İndirim (İsteğe Bağlı)',
      AppLanguage.en: 'Discount (Optional)',
      AppLanguage.ar: 'خصم (اختياري)',
      AppLanguage.ku: 'داشکاندن (ئارەزوومەندانە)',
      AppLanguage.uz: 'Chegirma (Ixtiyoriy)',
      AppLanguage.az: 'Endirim (İstəyə bağlı)',
      AppLanguage.de: 'Rabatt (Optional)',
    },
    'discount_rate': {
      AppLanguage.tr: 'İndirim Oranı (%)',
      AppLanguage.en: 'Discount Rate (%)',
      AppLanguage.ar: 'نسبة الخصم (%)',
      AppLanguage.ku: 'ڕێژەی داشکاندن (%)',
      AppLanguage.uz: 'Chegirma foizi (%)',
      AppLanguage.az: 'Endirim faizi (%)',
      AppLanguage.de: 'Rabattsatz (%)',
    },
    'full_amount': {
      AppLanguage.tr: 'Tam Tutar',
      AppLanguage.en: 'Full Amount',
      AppLanguage.ar: 'المبلغ الكامل',
      AppLanguage.ku: 'بڕی تەواو',
      AppLanguage.uz: 'To\'liq summa',
      AppLanguage.az: 'Tam məbləğ',
      AppLanguage.de: 'Gesamtbetrag',
    },
    'complete_payment': {
      AppLanguage.tr: 'Complete Payment',
      AppLanguage.en: 'Complete Payment',
      AppLanguage.ar: 'إتمام الدفع',
      AppLanguage.ku: 'تەواوکردنی پارەدان',
      AppLanguage.uz: 'To\'lovni yakunlash',
      AppLanguage.az: 'Ödəməni tamamla',
      AppLanguage.de: 'Zahlung abschließen',
    },
    'receive_payment': {
      AppLanguage.tr: 'Ödeme Al',
      AppLanguage.en: 'Receive Payment',
      AppLanguage.ar: 'استلام الدفع',
      AppLanguage.ku: 'وەرگرتنی پارە',
      AppLanguage.uz: 'To\'lov qabul qilish',
      AppLanguage.az: 'Ödəmə al',
      AppLanguage.de: 'Zahlung erhalten',
    },
    'payment_summary': {
      AppLanguage.tr: 'ÖDEME ÖZETİ',
      AppLanguage.en: 'PAYMENT SUMMARY',
      AppLanguage.ar: 'ملخص الدفع',
      AppLanguage.ku: 'پوختەی پارەدان',
      AppLanguage.uz: 'TO\'LOV XULASASI',
      AppLanguage.az: 'ÖDƏMƏ XÜLASƏSİ',
      AppLanguage.de: 'ZAHLUNGSÜBERSICHT',
    },
    'currency_rates': {
      AppLanguage.tr: 'Para Birimi & Kurlar',
      AppLanguage.en: 'Currency & Rates',
      AppLanguage.ar: 'العملة والأسعار',
      AppLanguage.ku: 'دراو و نرخەکان',
      AppLanguage.uz: 'Valyuta va kurslar',
      AppLanguage.az: 'Valyuta və məzənnə',
      AppLanguage.de: 'Währung & Kurse',
    },
    'receipt_type': {
      AppLanguage.tr: 'FİŞ TÜRÜ',
      AppLanguage.en: 'RECEIPT TYPE',
      AppLanguage.ar: 'نوع الإيصال',
      AppLanguage.ku: 'جۆری پسوولە',
      AppLanguage.uz: 'CHEK TURI',
      AppLanguage.az: 'ÇEK NÖVÜ',
      AppLanguage.de: 'BELEGTYP',
    },
    'bill_receipt': {
      AppLanguage.tr: 'Hesap fişi',
      AppLanguage.en: 'Bill receipt',
      AppLanguage.ar: 'إيصال الفاتورة',
      AppLanguage.ku: 'پسوولەی حساب',
      AppLanguage.uz: 'Hisob cheki',
      AppLanguage.az: 'Hesab çeki',
      AppLanguage.de: 'Rechnungsbeleg',
    },
    'kitchen_receipt': {
      AppLanguage.tr: 'Mutfak fişi',
      AppLanguage.en: 'Kitchen receipt',
      AppLanguage.ar: 'إيصال المطبخ',
      AppLanguage.ku: 'پسوولەی چێشتخانە',
      AppLanguage.uz: 'Oshxona cheki',
      AppLanguage.az: 'Mətbəx çeki',
      AppLanguage.de: 'Küchenbon',
    },
    'language': {
      AppLanguage.tr: 'DİL',
      AppLanguage.en: 'LANGUAGE',
      AppLanguage.ar: 'اللغة',
      AppLanguage.ku: 'زمان',
      AppLanguage.uz: 'TIL',
      AppLanguage.az: 'DİL',
      AppLanguage.de: 'SPRACHE',
    },
    'preview': {
      AppLanguage.tr: 'Önizlemeye geç',
      AppLanguage.en: 'Go to preview',
      AppLanguage.ar: 'معاينة',
      AppLanguage.ku: 'پێشبینین',
      AppLanguage.uz: 'Ko\'rib chiqish',
      AppLanguage.az: 'Önizləmə',
      AppLanguage.de: 'Vorschau',
    },
    'print_80mm': {
      AppLanguage.tr: '80mm Yazdır',
      AppLanguage.en: '80mm Print',
      AppLanguage.ar: 'طباعة 80mm',
      AppLanguage.ku: 'چاپی 80mm',
      AppLanguage.uz: '80mm Chop',
      AppLanguage.az: '80mm Çap',
      AppLanguage.de: '80mm Druck',
    },
    'print_80mm_desc': {
      AppLanguage.tr: 'Fiş türü ve dil seçin',
      AppLanguage.en: 'Select receipt type and language',
      AppLanguage.ar: 'اختر نوع الإيصال واللغة',
      AppLanguage.ku: 'جۆری پسوولە و زمان هەڵبژێرە',
      AppLanguage.uz: 'Chek turi va tilni tanlang',
      AppLanguage.az: 'Çek növü və dil seçin',
      AppLanguage.de: 'Belegtyp und Sprache wählen',
    },
    'staff': {
      AppLanguage.tr: 'PERSONEL',
      AppLanguage.en: 'STAFF',
      AppLanguage.ar: 'الموظفين',
      AppLanguage.ku: 'کارمەندان',
      AppLanguage.uz: 'XODIMLAR',
      AppLanguage.az: 'PERSONAL',
      AppLanguage.de: 'PERSONAL',
    },
    'admin': {
      AppLanguage.tr: 'YÖNETİCİ',
      AppLanguage.en: 'ADMIN',
      AppLanguage.ar: 'المدير',
      AppLanguage.ku: 'بەڕێوەبەر',
      AppLanguage.uz: 'ADMINISTRATOR',
      AppLanguage.az: 'ADMİN',
      AppLanguage.de: 'ADMIN',
    },
  };
}
